# -*- coding: utf-8 -*-
"""report-quality-date.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BdVssoYVa-iBZSfto72eHUK5yKscBdCu

#Relatório Data Quality
"""

!pip install great_expectations

import pandas as pd
import os
import great_expectations as gx

#dados de customers
olist_customers = pd.read_csv('content/datasets/olist_customers_dataset.csv')

print("Nomes das Colunas:")
print(olist_customers.columns)

print("\nPrimeiras 5 linhas do DataFrame:")
olist_customers.head()

olist_customers.info()

olist_customers = gx.read_csv('content/datasets/olist_customers_dataset.csv')

olist_customers.expect_column_values_to_be_null('customer_state')

# dados de geolocation
olist_geolocation = pd.read_csv('content/datasets/olist_geolocation_dataset.csv')

print("Nomes das Colunas:")
print(olist_geolocation.columns)

print("\nPrimeiras 5 linhas do DataFrame:")
olist_geolocation.head()

olist_geolocation.info()

# dados order items
olist_items = pd.read_csv('content/datasets/olist_order_items_dataset.csv')

print("Nomes das Colunas:")
print(olist_items.columns)

print("\nPrimeiras 5 linhas do DataFrame:")
olist_items.head()

olist_items.info()

# dados orders
olist_orders = pd.read_csv('content/datasets/olist_orders_dataset.csv')

#difindo expectativas
olist_orders.head()

olist_orders = gx.read_csv('content/datasets/olist_orders_dataset.csv')

#defindo expectativas
olist_orders.expect_column_values_to_be_unique('order_id')

olist_orders.expect_column_values_to_not_be_null('customer_id')

olist_orders.expect_column_values_to_be_in_set('order_status', ['delivered', 'canceled', 'processing', 'shipped', 'invoiced'])

olist_orders.expect_column_values_to_match_strftime_format('order_purchase_timestamp', '%Y-%m-%d %H:%M:%S')

#dados pagamento
olist_payments = pd.read_csv('content/datasets/olist_order_payments_dataset.csv')

olist_payments.head()

olist_payments = gx.read_csv('content/datasets/olist_order_payments_dataset.csv')

#expectativas pagamento
olist_payments.expect_column_values_to_be_between('payment_value', 0, None)

olist_payments.expect_column_value_lengths_to_be_between('payment_type', 3, 20)

